version: '3.7'

services:
  api:
    container_name: container_api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports: 
      - "3333:3333"
    container_name: container_api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:5.0.5-alpine
    restart: always
    volumes:
      - redis_data:/data
volumes:
  redis_data:
  