version: '3.7'

services:
  app:
    container_name: container_app
    build: 
      context: .
      dockerfile: apps/app/Dockerfile.dockerdev
    restart: always
    ports: 
      - "8080:8080"
    volumes:
      - ./:/usr/web/app/
      - ./node_modules:/usr/web/app/node_modules
    depends_on:
      - api
  