version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/comunitius
    steps:
      - checkout
      - save_cache:
          key: v001-comunitius-{{ checksum "package-lock.json" }}
          paths: 
            - .
      - restore_cache:
          keys:
            - v001-comunitius-{{ checksum "package-lock.json" }}
            - v001-comunitius
      - run:
          name: front-end unit tests
          command: npm install && npm run test
      - run:
          name: front-end build for production
          command:  npm run build