# Stage 0
# Frontend build based on Node.js
FROM node:lts-alpine as builder

RUN mkdir -p /usr/web/app

WORKDIR /usr/web/app

ENV PATH /usr/web/app/node_modules/.bin:$PATH

COPY package.json /usr/web/app/package.json
COPY package-lock.json /usr/web/app/package-lock.json
  
RUN npm install

CMD [ "npm", "start", "app" ]
